sudo: required
language: cpp
services:
  - docker
env:
  - TEST_CMSSW_VERSION=CMSSW_8_0_28_patch1 SCRAM_ARCH=slc6_amd64_gcc530
  - TEST_CMSSW_VERSION=CMSSW_9_2_4 SCRAM_ARCH=slc6_amd64_gcc530
compiler:
  - gcc
before_install:
  - docker pull claria/cvmfs-cms
script:
  - docker run --privileged -e TEST_CMSSW_VERSION=${TEST_CMSSW_VERSION}
                            -e SCRAM_ARCH=${SCRAM_ARCH}
                            -v ${TRAVIS_BUILD_DIR}:/home/travis claria/cvmfs-cms /bin/bash 
                            -c "cd /home/; /home/travis/test/test_build.sh"
